export enum EventName {
	Ready = 'ready',
	GuildCreate = 'guildCreate',
	GuildDelete = 'guildDelete',
	GuildMemberAdd = 'guildMemberAdd',
	InteractionCreate = 'interactionCreate',
	VoiceStateUpdate = 'voiceStateUpdate',
}

export enum CommandName {
	Birthdays = 'birthdays',
	Channels = 'channels',
	Comics = 'comics',
	Deals = 'deals',
	HowLongToBeat = 'hltb',
	Integrations = 'integrations',
	Jokes = 'jokes',
	Memes = 'memes',
	Movies = 'movies',
	Music = 'music',
	Poll = 'poll',
	Prune = 'prune',
	Reminders = 'reminders',
	Reviews = 'reviews',
	Roles = 'roles',
	SecretSanta = 'secret-santa',
	Series = 'series',
	Steam = 'steam',
	Subscriptions = 'subscriptions',
	Webhooks = 'webhooks',
	Xbox = 'xbox',
	Youtube = 'youtube',
}

export enum JobName {
	Anime = 'anime',
	Birthdays = 'birthdays',
	BreakingNews = 'breakingNews',
	Deals = 'deals',
	GamingNews = 'gamingNews',
	Leaderboards = 'leaderboards',
	Manga = 'manga',
	Memes = 'memes',
	Nintendo = 'nintendo',
	Nsfw = 'nsfw',
	PlayStation = 'playstation',
	Reminders = 'reminders',
	Reviews = 'reviews',
	Roles = 'roles',
	Subscriptions = 'subscriptions',
	Wishlists = 'wishlists',
	Xbox = 'xbox',
}
