export type Country =
	| 'Argentina'
	| 'Australia'
	| 'Austria'
	| 'Bangladesh'
	| 'Belgium'
	| 'Brazil'
	| 'Bulgaria'
	| 'Canada'
	| 'Chile'
	| 'China'
	| 'Colombia'
	| 'Cuba'
	| 'Czech Republic'
	| 'Egypt'
	| 'France'
	| 'Germany'
	| 'Greece'
	| 'Hong kong'
	| 'Hungary'
	| 'India'
	| 'Indonesia'
	| 'Iraq'
	| 'Ireland'
	| 'Israel'
	| 'Italy'
	| 'Japan'
	| 'Kazakhstan'
	| 'Latvia'
	| 'Lebanon'
	| 'Lithuania'
	| 'Malaysia'
	| 'Mexico'
	| 'Morocco'
	| 'Netherland'
	| 'New Zealand'
	| 'Nigeria'
	| 'North Korea'
	| 'Norway'
	| 'Pakistan'
	| 'Peru'
	| 'Philippines'
	| 'Poland'
	| 'Portugal'
	| 'Romania'
	| 'Russia'
	| 'Saudi Arabia'
	| 'Serbia'
	| 'Singapore'
	| 'Slovakia'
	| 'Slovenia'
	| 'South africa'
	| 'South korea'
	| 'Spain'
	| 'Sweden'
	| 'Switzerland'
	| 'Taiwan'
	| 'Thailand'
	| 'Turkey'
	| 'Ukraine'
	| 'United Arab Emirates'
	| 'United Kingdom'
	| 'United States of America'
	| 'Venezuela';
